services:
  # This is your main Web Application
  - type: web
    name: attendance-app
    env: node
    plan: free
    buildCommand: "npm install && cd frontend && npm install && npm run build"
    startCommand: "node backend/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: DATABASE_URL
        fromService:
          type: psql
          name: attendance-db # <-- Use the exact name you gave your database on Render
          property: internalUrl

  # This defines your PostgreSQL Database
  - type: psql
    name: attendance-db # <-- Use the exact name you gave your database on Render
    plan: free